/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Chat: typeof import('./src/components/chat/Chat.vue')['default']
    DeviceSelect: typeof import('./src/components/chatroom/DeviceSelect.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    Join: typeof import('./src/components/chatroom/Join.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    MemberList: typeof import('./src/components/chatroom/MemberList.vue')['default']
    MessageFile: typeof import('./src/components/chat/MessageFile.vue')['default']
    MessageList: typeof import('./src/components/chat/MessageList.vue')['default']
    Scrollbar: typeof import('./src/components/scrollbar.vue')['default']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
  }
}
